tasks:
  - init: ./ContextMapper/app/gradlew clean build
image:
  file: /ContextMapper/app/.gitpod.Dockerfile
vscode:
  extensions:
    - contextmapper.context-mapper-vscode-extension
    - jebbs.plantuml
